apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: wireguard
  namespace: flux-system
spec:
  dependsOn:
    - name: wireguard-pre-deploy
    - name: kube-system
  interval: 1h
  path: ./flux-modules/extras/wireguard/deploy
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  postBuild:
    substitute:
      k8s_service_cidr: "10.96.0.0/16"
