apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-operator
spec:
  interval: 1h
  chart:
    spec:
      chart: mariadb-operator
      version: "0.${mariadb_operator_version}"
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
        namespace: db
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    webhook:
      enabled: true
      cert:
        certManager:
          enabled: true
      serviceMonitor:
        enabled: true
