apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
  envFrom:
    - configMapRef:
        name: mariadb-config
  metrics:
    enabled: true
    passwordSecretKeyRef:
      key: password
      name: mariadb-metrics-password
    username: mariadb-metrics
    exporter:
      image: docker.io/prom/mysqld-exporter:v0.15.1
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 65534
        capabilities:
          drop: ["ALL"]
  myCnf: |
    [mysqld]
    bind-address=0.0.0.0
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    max_allowed_packet=256M
  myCnfConfigMapKeyRef:
    key: my.cnf
    name: mariadb-my-cnf
  port: 3306
  replicas: 1
  rootEmptyPassword: false
  rootPasswordSecretKeyRef:
    key: root-password
    name: mariadb-password
  updateStrategy:
    autoUpdateDataPlane: true
  podSecurityContext:
    runAsUser: 999
    runAsGroup: 999
    runAsNonRoot: true
    fsGroup: 999
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    capabilities:
      drop: ["ALL"]
  serviceAccountName: mariadb
  storage:
    size: 10Gi
    volumeClaimTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: local-storage
