apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-local-storage
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem # Mount volume into Pod as a directory.
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /srv/mariadb/
  nodeAffinity: # nodeAffinity is required when using local volumes.
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.kubernetes.io/zone
              operator: In
              values:
                - EU-FRANKFURT-1-AD-1
