apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kube-system-extra
  namespace: flux-system
spec:
  dependsOn:
    - name: kube-system
  interval: 1h
  path: ./flux-modules/kube-system-extra
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  postBuild:
    substitute:
      admin_email: "admin@email.com"
