apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: paperless
  namespace: flux-system
spec:
  dependsOn:
    - name: paperless-pre-deploy
    - name: mariadb
    - name: kube-system-extra
  interval: 1h
  path: ./flux-modules/extras/paperless/deploy
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  postBuild:
    substitute:
      db_name: paperless
      db_userpass_secret: db-paperless-user-pass
      db_max_connections: "40"
