apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: cert-manager
      version: '>=1.9.1'
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: kube-system
  values:
    installCRDs: true
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
