apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator
  namespace: flux-system
spec:
  interval: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  timeout: 5m
  driftDetection:
    mode: enabled
  releaseName: flux-operator
  chartRef:
    kind: OCIRepository
    name: flux-operator
