apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: mariadb
  namespace: flux-system
spec:
  dependsOn:
    - name: mariadb-pre-deploy
    - name: kube-system
  interval: 1h
  path: ./flux-modules/extras/mariadb/deploy
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
