apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wireguard
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - storage.yaml
  - server-init-file-cm.yaml
patches:
  - path: user-settings-patch.yaml
    target:
      kind: Deployment
      name: wireguard
