apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: monitoring-flux
  namespace: flux-system
spec:
  dependsOn:
    - name: monitoring
  interval: 1h
  path: ./flux-modules/monitoring/flux
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
