apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: oci-infra-repo
  namespace: flux-system
spec:
  # provider type can be github or gitlab
  type: github
  address: ${https_repo_url}
  secretRef:
    name: github-api-token
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: flux-system-kustomization
  namespace: flux-system
spec:
  providerRef:
    name: oci-infra-repo
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: "*"
      namespace: flux-system
