apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
spec:
  interval: 5m
  chart:
    spec:
      version: "1.x.x"
      chart: cilium
      sourceRef:
        kind: HelmRepository
        name: cilium
      interval: 120m
  values:
    hubble:
      enabled: true
      metrics:
        dashboards:
          enabled: true
          namespace: kube-system
      relay:
        enabled: true
      ui:
        enabled: true
    ipam:
      mode: "kubernetes"
    #clustermesh:
    #  useAPIServer: true
